### ISSUE TITLE
Document install script

### ISSUE THREAD

**Issue by bbockelm** [HTPhenotyping/execute_node_config#6]
After #4 is merged, please update the instructions here:

https://htpheno-cm.chtc.wisc.edu/installation.html

**Comment by jasoncpatton** [comment]
Done for the install script. Will need to be updated with either instructions to run `register.py` or whatever else needs to be added once `register.py` is part of the install script.

**Comment by jasoncpatton** [comment]
Leave feedback here (or Slack... or email... whatever works)

**Comment by jasoncpatton** [comment]
There is still some cleaning up to do, like adding padding to the screenshots and making better screenshots, but for the first few demos, this looks usable.
